id: I3EFEA228
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-d943
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 11:27:50.388696+00:00
last_modified: 2023-09-28 11:27:50.388701+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN22840
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN22840
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མའི་བསྟན་བཅོས་ཆེན་པོ་རིགས་པའི་རྒྱན་གྱི་མུན་སེལ།
  languages:
  - bo
  author: དགེ་འདུན་གྲུབ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9985090047729855
  ocr_word_median_confidence_index: 1.0
bases:
  I4CN10264:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CN10264
      total_pages: 358
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CN10264.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9985090047729855
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
